/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vxi11.h"


void
device_async_1(char *host)
{
	CLIENT *clnt;
	Device_Error  *result_1;
	Device_Link  device_abort_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DEVICE_ASYNC, DEVICE_ASYNC_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = device_abort_1(&device_abort_1_arg, clnt);
	if (result_1 == (Device_Error *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
device_core_1(char *host)
{
	CLIENT *clnt;
	Create_LinkResp  *result_1;
	Create_LinkParms  create_link_1_arg;
	Device_WriteResp  *result_2;
	Device_WriteParms  device_write_1_arg;
	Device_ReadResp  *result_3;
	Device_ReadParms  device_read_1_arg;
	Device_ReadStbResp  *result_4;
	Device_GenericParms  device_readstb_1_arg;
	Device_Error  *result_5;
	Device_GenericParms  device_trigger_1_arg;
	Device_Error  *result_6;
	Device_GenericParms  device_clear_1_arg;
	Device_Error  *result_7;
	Device_GenericParms  device_remote_1_arg;
	Device_Error  *result_8;
	Device_GenericParms  device_local_1_arg;
	Device_Error  *result_9;
	Device_LockParms  device_lock_1_arg;
	Device_Error  *result_10;
	Device_Link  device_unlock_1_arg;
	Device_Error  *result_11;
	Device_EnableSrqParms  device_enable_srq_1_arg;
	Device_DocmdResp  *result_12;
	Device_DocmdParms  device_docmd_1_arg;
	Device_Error  *result_13;
	Device_Link  destroy_link_1_arg;
	Device_Error  *result_14;
	Device_RemoteFunc  create_intr_chan_1_arg;
	Device_Error  *result_15;
	char *destroy_intr_chan_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DEVICE_CORE, DEVICE_CORE_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = create_link_1(&create_link_1_arg, clnt);
	if (result_1 == (Create_LinkResp *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = device_write_1(&device_write_1_arg, clnt);
	if (result_2 == (Device_WriteResp *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = device_read_1(&device_read_1_arg, clnt);
	if (result_3 == (Device_ReadResp *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = device_readstb_1(&device_readstb_1_arg, clnt);
	if (result_4 == (Device_ReadStbResp *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = device_trigger_1(&device_trigger_1_arg, clnt);
	if (result_5 == (Device_Error *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = device_clear_1(&device_clear_1_arg, clnt);
	if (result_6 == (Device_Error *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = device_remote_1(&device_remote_1_arg, clnt);
	if (result_7 == (Device_Error *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = device_local_1(&device_local_1_arg, clnt);
	if (result_8 == (Device_Error *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = device_lock_1(&device_lock_1_arg, clnt);
	if (result_9 == (Device_Error *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = device_unlock_1(&device_unlock_1_arg, clnt);
	if (result_10 == (Device_Error *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = device_enable_srq_1(&device_enable_srq_1_arg, clnt);
	if (result_11 == (Device_Error *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = device_docmd_1(&device_docmd_1_arg, clnt);
	if (result_12 == (Device_DocmdResp *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_13 = destroy_link_1(&destroy_link_1_arg, clnt);
	if (result_13 == (Device_Error *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_14 = create_intr_chan_1(&create_intr_chan_1_arg, clnt);
	if (result_14 == (Device_Error *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_15 = destroy_intr_chan_1((void*)&destroy_intr_chan_1_arg, clnt);
	if (result_15 == (Device_Error *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
device_intr_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	Device_SrqParms  device_intr_srq_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DEVICE_INTR, DEVICE_INTR_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = device_intr_srq_1(&device_intr_srq_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	device_async_1 (host);
	device_core_1 (host);
	device_intr_1 (host);
exit (0);
}
